// <auto-generated />
using System;
using Football247.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Football247.Infrastructure.Migrations
{
    [DbContext(typeof(Football247DbContext))]
    [Migration("20260517121100_tables_in_store_func")]
    partial class tables_in_store_func
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Football247.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<string>("AwayTeamCrest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AwayTeamExternalId")
                        .HasColumnType("int");

                    b.Property<string>("AwayTeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AwayTeamShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompetitionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompetitionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<int>("ExternalId")
                        .HasColumnType("int");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<string>("HomeTeamCrest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HomeTeamExternalId")
                        .HasColumnType("int");

                    b.Property<string>("HomeTeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeTeamShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<int>("Matchday")
                        .HasColumnType("int");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("UtcDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_Matches_ExternalId");

                    b.HasIndex("UtcDate");

                    b.HasIndex("CompetitionCode", "Season", "Status")
                        .HasDatabaseName("IX_Matches_Listing_Optimized");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Football247.Domain.Entities.NotificationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<Guid?>("ObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RedirectUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("NotificationMessages");
                });

            modelBuilder.Entity("Football247.Domain.Entities.Standing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("CompetitionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<int>("Draw")
                        .HasColumnType("int");

                    b.Property<int>("GoalDifference")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Lost")
                        .HasColumnType("int");

                    b.Property<int>("PlayedGames")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<string>("TeamCrest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamExternalId")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.Property<int>("Won")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionCode", "Season", "Position")
                        .IsUnique()
                        .HasDatabaseName("IX_Standings_Competition_Season_Position");

                    b.ToTable("Standings");
                });

            modelBuilder.Entity("Football247.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Football247.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<bool>("ReceiveEmailNotifications")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceiveInAppNotifications")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpinCount")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Football247.Models.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("BgrImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsApproved")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Articles_Slug");

                    b.HasIndex("TeamId");

                    b.HasIndex("ViewCount");

                    b.HasIndex("CategoryId", "IsApproved");

                    b.HasIndex("CategoryId", "IsApproved", "CreatedDate")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_Articles_Listing_Optimized");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b9b0db97-6e0d-4428-b826-249aafda76e6"),
                            BgrImage = "",
                            CategoryId = new Guid("091a6e9c-b9d6-4854-9eb5-8239f1501a9f"),
                            Content = "Inter Milan đã đánh bại Barcelona bằng tổng tỷ số 7-6 sau hai lượt trận bán kết, qua đó góp mặt ở chung kết Champions League......",
                            CreatedDate = new DateTime(2025, 5, 7, 16, 38, 39, 658, DateTimeKind.Utc),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Mehdi Taremi, cầu thủ từng khiến tuyển thủ Việt Nam Phạm Đức Huy bị mất trí nhớ cách đây 7 năm, có thể đi vào lịch sử bóng đá Iran tại Champions League.",
                            IsApproved = 1,
                            IsDeleted = false,
                            Priority = 1,
                            Slug = "sao-inter-milan-tung-khien-tuyen-thu-viet-nam-mat-ket-noi",
                            Status = 0,
                            Title = "Sao Inter Milan từng khiến tuyển thủ Việt Nam 'mất kết nối'",
                            ViewCount = 0
                        },
                        new
                        {
                            Id = new Guid("b9b0db97-6e0d-4428-b826-249aafda76e7"),
                            BgrImage = "",
                            CategoryId = new Guid("811d5c7d-30ba-4dd9-b479-505a65a217cf"),
                            Content = "Las Palmas và Rayo Vallecano lúc này đang ở vị thế rất khác nhau. Nếu như Vallecano đang nằm trong nhóm được dự cúp châu Âu mùa sau (đứng thứ 8) thì Las Palmas lại phải đối mặt với nguy cơ xuống hạng.",
                            CreatedDate = new DateTime(2025, 5, 7, 16, 38, 39, 658, DateTimeKind.Utc),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Nhận định bóng đá trận Las Palmas vs Vallecano diễn ra vào lúc 02h00 ngày 10/5 trong khuôn khổ vòng 35 La Liga 2024/25. Bongdaplus phân tích thông tin lực lượng, đội hình dự kiến, soi kèo nhà cái, dự đoán tỉ số.",
                            IsApproved = 1,
                            IsDeleted = false,
                            Priority = 1,
                            Slug = "nhan-dinh-bong-da-las-palmas-vs-vallecano-02h00-ngay-10-5-suc-manh-ke-khon-cung",
                            Status = 0,
                            Title = "Nhận định bóng đá Las Palmas vs Vallecano, 02h00 ngày 10/5: Sức mạnh kẻ khốn cùng\r\n",
                            ViewCount = 0
                        });
                });

            modelBuilder.Entity("Football247.Models.Entities.ArticleTag", b =>
                {
                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.HasKey("ArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ArticleTags");

                    b.HasData(
                        new
                        {
                            ArticleId = new Guid("b9b0db97-6e0d-4428-b826-249aafda76e6"),
                            TagId = new Guid("56ba2d79-f7bb-4be0-8d7b-12be4ad20335"),
                            CreatedDate = new DateTime(2025, 5, 7, 16, 38, 39, 658, DateTimeKind.Utc),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false
                        },
                        new
                        {
                            ArticleId = new Guid("b9b0db97-6e0d-4428-b826-249aafda76e7"),
                            TagId = new Guid("85fb19e4-2bda-4d34-b92c-f116e8a3166b"),
                            CreatedDate = new DateTime(2025, 5, 7, 16, 38, 39, 658, DateTimeKind.Utc),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Football247.Models.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Categorys_Slug");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("091a6e9c-b9d6-4854-9eb5-8239f1501a9f"),
                            CreatedDate = new DateTime(2025, 5, 7, 16, 38, 39, 658, DateTimeKind.Utc),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Name = "CHAMPIONS LEAGUE",
                            Slug = "champions-league"
                        },
                        new
                        {
                            Id = new Guid("811d5c7d-30ba-4dd9-b479-505a65a217cf"),
                            CreatedDate = new DateTime(2025, 5, 7, 16, 38, 39, 658, DateTimeKind.Utc),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Name = "SPAIN ",
                            Slug = "spain"
                        });
                });

            modelBuilder.Entity("Football247.Models.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Football247.Models.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b085068-d940-458b-87f8-fae4cb132139"),
                            ArticleId = new Guid("b9b0db97-6e0d-4428-b826-249aafda76e6"),
                            Caption = "Mehdi Taremi trong màu áo Porto",
                            DisplayOrder = 1,
                            ImageExtension = "jpg",
                            ImageUrl = "/images/sao-inter.jpg",
                            UploadedAt = new DateTime(2025, 5, 7, 16, 38, 39, 658, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5d968e39-4dd8-4e14-89c3-924b65d2dc05"),
                            ArticleId = new Guid("b9b0db97-6e0d-4428-b826-249aafda76e6"),
                            Caption = "Phạm Đức Huy trong một pha tranh chấp",
                            DisplayOrder = 2,
                            ImageExtension = "jpg",
                            ImageUrl = "/images/duc-huy.jpg",
                            UploadedAt = new DateTime(2025, 5, 7, 16, 38, 39, 658, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Football247.Models.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_Slug");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Football247.Models.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnOrder(107);

                    b.Property<string>("CreatedFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(104);

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(109);

                    b.Property<string>("DeletedFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(106);

                    b.Property<Guid?>("DeletedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnOrder(110);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(108);

                    b.Property<string>("UpdatedFullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(105);

                    b.Property<Guid?>("UpdatedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(102);

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Tags_Slug");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("56ba2d79-f7bb-4be0-8d7b-12be4ad20335"),
                            CreatedDate = new DateTime(2025, 5, 7, 16, 38, 39, 658, DateTimeKind.Utc),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Name = "MU",
                            Slug = "mu-tags"
                        },
                        new
                        {
                            Id = new Guid("85fb19e4-2bda-4d34-b92c-f116e8a3166b"),
                            CreatedDate = new DateTime(2025, 5, 7, 16, 38, 39, 658, DateTimeKind.Utc),
                            CreatedFullName = "",
                            CreatedUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Name = "Las Palmas",
                            Slug = "las-palmas-tags"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Football247.Models.Entities.Article", b =>
                {
                    b.HasOne("Football247.Models.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Football247.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.Navigation("Category");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Football247.Models.Entities.ArticleTag", b =>
                {
                    b.HasOne("Football247.Models.Entities.Article", "Article")
                        .WithMany("ArticleTags")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Football247.Models.Entities.Tag", "Tag")
                        .WithMany("ArticleTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Football247.Models.Entities.Comment", b =>
                {
                    b.HasOne("Football247.Models.Entities.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Football247.Models.Entities.Image", b =>
                {
                    b.HasOne("Football247.Models.Entities.Article", "Article")
                        .WithMany("Images")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Football247.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("Football247.Models.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Football247.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Football247.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Football247.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Football247.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Football247.Models.Entities.Article", b =>
                {
                    b.Navigation("ArticleTags");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Football247.Models.Entities.Tag", b =>
                {
                    b.Navigation("ArticleTags");
                });
#pragma warning restore 612, 618
        }
    }
}
